"""Kontext-Profile: BAU, HEALTH, CUSTOMS, SUBSIDY, JUSTICE."""

CONTEXT_PROFILES = {
    "BAU": {
        "description": "Bauabnahme nach VOB/B",
        "required_roles": {"initiator": "CONTRACTOR_CEO", "approver": "CITY_INSPECTOR"},
        "tax_rate": 0.15, "tax_name": "Bauabzugssteuer (§48b EStG)",
        "retention_rate": 0.05, "retention_name": "Sicherheitseinbehalt (§17 VOB/B)",
        "retention_years": 4,
        "tax_wallet": "0xFINANZAMT_BAU", "escrow_wallet": "0xSTADT_ESCROW",
        "estimated_amount": 45000.0, "cost_center": "KOST_A12_BAU",
        "legal_basis": "VOB/B §§13,16,17",
    },
    "HEALTH": {
        "description": "Krankenhausabrechnung (SGB V)",
        "required_roles": {"initiator": "ATTENDING_PHYSICIAN", "approver": "HEALTH_INSURANCE_REP"},
        "tax_rate": 0.0, "tax_name": "USt-frei (§4 Nr.14 UStG)",
        "retention_rate": 0.10, "retention_name": "MDK-Prüfvorbehalt",
        "retention_years": 2,
        "tax_wallet": "0xGKV_SPITZENVERBAND", "escrow_wallet": "0xMDK_ESCROW",
        "estimated_amount": 12500.0, "cost_center": "KOST_MED_001",
        "legal_basis": "SGB V §301,302",
    },
    "CUSTOMS": {
        "description": "Zollabfertigung / Einfuhrumsatzsteuer",
        "required_roles": {"initiator": "IMPORTER", "approver": "CUSTOMS_OFFICER"},
        "tax_rate": 0.19, "tax_name": "Einfuhrumsatzsteuer",
        "retention_rate": 0.0, "retention_name": "Keine",
        "retention_years": 0,
        "tax_wallet": "0xDEUTSCHER_ZOLL", "escrow_wallet": "0xNULL",
        "estimated_amount": 8750.0, "cost_center": "KOST_ZOLL_001",
        "legal_basis": "UZK Art.5, UStG §21",
    },
    "SUBSIDY": {
        "description": "Förderauszahlung (KfW/BAFA/EU)",
        "required_roles": {"initiator": "CITIZEN", "approver": "AGENCY_OFFICER"},
        "tax_rate": 0.0, "tax_name": "Keine",
        "retention_rate": 0.0, "retention_name": "Keine",
        "retention_years": 0,
        "tax_wallet": "0xNULL", "escrow_wallet": "0xNULL",
        "estimated_amount": 15000.0, "cost_center": "KOST_FOERDERUNG",
        "legal_basis": "BHO §44, VV-BHO",
    },
    "JUSTICE": {
        "description": "Gerichtskosten / Prozesskautionen",
        "required_roles": {"initiator": "PLAINTIFF_LAWYER", "approver": "JUDGE"},
        "tax_rate": 0.0, "tax_name": "Keine",
        "retention_rate": 1.0, "retention_name": "Prozesskautions-Sperre",
        "retention_years": 10,
        "tax_wallet": "0xNULL", "escrow_wallet": "0xGERICHTSKASSE",
        "estimated_amount": 50000.0, "cost_center": "KOST_JUSTIZ",
        "legal_basis": "GKG, ZPO §§91ff",
    },
}
