"""Kontext-Profile für den B2G Universal Ledger — BAU, HEALTH, CUSTOMS, SUBSIDY, JUSTICE."""

CONTEXT_PROFILES = {
    "BAU": {
        "description": "Bauabnahme nach VOB/B",
        "required_roles": {"initiator": "CONTRACTOR_CEO", "approver": "CITY_INSPECTOR"},
        "legal_basis": "VOB/B §§ 13, 16, 17",
        "tax_rate": 0.15, "tax_name": "Bauabzugssteuer (§48 EStG)",
        "retention_rate": 0.05, "retention_name": "Sicherheitseinbehalt (§17 VOB/B)",
        "retention_years": 4,
        "tax_wallet": "0xFINANZAMT_BAU",
        "escrow_wallet": "0xSTADT_ESCROW",
        "timelock_days": 30, "appeal_window_days": 14,
        "success_message": "✅ Baumeilenstein bestätigt. Geld ist auf dem Weg – inkl. Steuer und Einbehalt.",
        "milestone_types": ["fundament", "rohbau", "dach", "innenausbau", "abnahme"],
    },
    "HEALTH": {
        "description": "Abrechnung von Krankenhausbehandlungen (SGB V)",
        "required_roles": {"initiator": "ATTENDING_PHYSICIAN", "approver": "HEALTH_INSURANCE_REP"},
        "legal_basis": "SGB V §301, §302",
        "tax_rate": 0.0, "tax_name": "USt.-befreit (§4 Nr.14 UStG)",
        "retention_rate": 0.10, "retention_name": "Prüfvorbehalt MDK",
        "retention_years": 2,
        "tax_wallet": "0xNULL",
        "escrow_wallet": "0xMDK_ESCROW",
        "timelock_days": 7, "appeal_window_days": 30,
        "success_message": "✅ Behandlung bestätigt. Krankenkasse überweist in 24h – Prüfvorbehalt gesperrt.",
        "milestone_types": ["aufnahme", "diagnose", "behandlung", "entlassung", "abrechnung"],
    },
    "SUBSIDY": {
        "description": "Auszahlung von Fördermitteln (KfW, BAFA, EU)",
        "required_roles": {"initiator": "CITIZEN", "approver": "AGENCY_OFFICER"},
        "legal_basis": "BHO §44, VV-BHO",
        "tax_rate": 0.0, "tax_name": "Keine",
        "retention_rate": 0.0, "retention_name": "Keine",
        "retention_years": 0,
        "tax_wallet": "0xNULL",
        "escrow_wallet": "0xNULL",
        "timelock_days": 0, "appeal_window_days": 30,
        "success_message": "✅ Förderung freigegeben. 100 % werden ausgezahlt.",
        "milestone_types": ["antrag", "bewilligung", "verwendung", "nachweis", "auszahlung"],
    },
    "CUSTOMS": {
        "description": "Zollabfertigung und Einfuhrumsatzsteuer",
        "required_roles": {"initiator": "IMPORTER", "approver": "CUSTOMS_OFFICER"},
        "legal_basis": "UZK Art. 5, UStG §21",
        "tax_rate": 0.19, "tax_name": "Einfuhrumsatzsteuer",
        "retention_rate": 0.0, "retention_name": "Keine",
        "retention_years": 0,
        "tax_wallet": "0xDEUTSCHER_ZOLL",
        "escrow_wallet": "0xNULL",
        "timelock_days": 1, "appeal_window_days": 30,
        "success_message": "✅ Zollabfertigung abgeschlossen. Ware ist freigegeben.",
        "milestone_types": ["deklaration", "pruefung", "berechnung", "zahlung", "freigabe"],
    },
    "JUSTICE": {
        "description": "Gerichtskosten und Kautionen",
        "required_roles": {"initiator": "PLAINTIFF_LAWYER", "approver": "JUDGE"},
        "legal_basis": "GKG, ZPO §§ 91ff",
        "tax_rate": 0.0, "tax_name": "Keine",
        "retention_rate": 1.0, "retention_name": "Prozesskautions-Sperre",
        "retention_years": 10,
        "tax_wallet": "0xNULL",
        "escrow_wallet": "0xGERICHTSKASSE",
        "timelock_days": 0, "appeal_window_days": 30,
        "success_message": "✅ Kaution hinterlegt. Verfahren ist eröffnet.",
        "milestone_types": ["klage", "erwiderung", "beweis", "urteil", "vollstreckung"],
    },
}
