global:
  scrape_interval: 1s
  evaluation_interval: 1s

scrape_configs:
  - job_name: "agentx-surface"
    static_configs:
      - targets: ["surface-agent:8080"]

  - job_name: "agentx-subsurface"
    static_configs:
      - targets: ["d01-mock-responder:8081"]

  - job_name: "agentx-infantry"
    static_configs:
      - targets: ["infantry:8082"]
