#!/usr/bin/env bash
# Agent X — nightly backup: compose + env + fresh SON + Neo4j dump + retention.
# Runs after SON regeneration so the fresh report is included.
set -euo pipefail
REPO="/Volumes/THX_OS_ULTRA/Users/olivermueller/agent_x_storage"
DEST="${HOME}/backup/agent-x-$(date +%Y%m%d-%H%M)"
KEEP=7
mkdir -p "${DEST}"
cd "${REPO}"
# 1) Compose, env, volume inventory
cp docker-compose.yml docker-compose.mock.yml .env "${DEST}/" 2>/dev/null || true
docker volume ls --format "table {{.Name}}\t{{.Driver}}" > "${DEST}/volumes.txt"
# 2) Fresh SON report (generated by the 03:00 cron before this)
cp archive_b2g/son_report.json "${DEST}/" 2>/dev/null || true
# 3) Neo4j dump — live dump fails ('database is in use'), so stop/dump/start
NEO4J_CTR="$(docker ps --filter name=neo4j --format '{{.Names}}' | head -1)"
NEO4J_VOL="$(docker inspect "${NEO4J_CTR}" \
  --format '{{range .Mounts}}{{if eq .Destination "/data"}}{{.Name}}{{end}}{{end}}')"
docker compose -f docker-compose.yml stop neo4j
docker run --rm --entrypoint neo4j-admin \
  -v "${NEO4J_VOL}:/data" -v "${DEST}:/backup" \
  neo4j:5.26-community database dump neo4j --to-path=/backup/
docker compose -f docker-compose.yml start neo4j
# 4) Wait until neo4j healthy again (max ~60s)
for _ in $(seq 1 30); do
  st="$(docker inspect --format '{{.State.Health.Status}}' "${NEO4J_CTR}" 2>/dev/null || echo starting)"
  [ "${st}" = "healthy" ] && break
  sleep 2
done
# 5) Retention — keep last ${KEEP}
ls -1dt "${HOME}"/backup/agent-x-* | tail -n +"$((KEEP + 1))" | xargs rm -rf -- 2>/dev/null || true
echo "backup complete: ${DEST}"
