{{- if and .Values.podDisruptionBudget.enabled (gt (int .Values.replicaCount) 0) }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "regime-swarm.fullname" . }}
  labels:
    {{- include "regime-swarm.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "regime-swarm.selectorLabels" . | nindent 6 }}
{{- end }}
